service: hello-world
frameworkVersion: '2'

plugins: 
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x


functions:
  hello:
    events:
      - http:
          method: get
          path: hello
    handler: handler.hello