service: node-typescript-apollo-lambda
frameworkVersion: '2'

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x

functions:
  graphql:
    handler:  src/handler.graphqlHandler
    events:
      - http:
          private:  true
          path: graphql
          method: post
      - http:
          private: true
          path: graphql
          method: get